=== rogalmic/vscode-xml-complete/test/Simple/Simple.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="addresses">
		<xs:annotation>
			<xs:documentation>This is the address collection.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="address">
		<xs:annotation>
			<xs:documentation>This is the single address entry.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="street" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string">
		<xs:annotation>
			<xs:documentation>This is the contact's name.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="street" type="xs:string">
		<xs:annotation>
			<xs:documentation>This is the contact's street name.</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== rogalmic/vscode-xml-complete/test/Simple/Simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<addresses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:///C:/Users\rogalmic\Documents\src\vscode-xml-complete\test\Simple\Simple.xsd">
<!-- notice the autocompletion descriptions from xsd documentation nodes -->
  <address>
    <name>Joe Tester</name>
    <street>Baker street 5</street>
    <wrongExtraField/>
  </address>
  <address>
    <name >Bill Kill</name>
    <street>By Drive 5</street>
  </address>
</addresses>
